//
// DisablePredictiveText.swift
// Auto-generated by expo config plugin
//
// This file disables the iOS predictive text bar for all TextInputs

import UIKit

// Extension to automatically disable predictive text on UITextField
extension UITextField {
  // Swizzle init(frame:) to disable predictive text
  static let swizzleInit: Void = {
    let originalSelector = #selector(UITextField.init(frame:))
    let swizzledSelector = #selector(UITextField.swizzled_init(frame:))
    
    guard let originalMethod = class_getInstanceMethod(UITextField.self, originalSelector),
          let swizzledMethod = class_getInstanceMethod(UITextField.self, swizzledSelector) else {
      return
    }
    
    method_exchangeImplementations(originalMethod, swizzledMethod)
  }()
  
  @objc private func swizzled_init(frame: CGRect) -> UITextField {
    let textField = self.swizzled_init(frame: frame)
    textField.autocorrectionType = .no
    textField.spellCheckingType = .no
    textField.smartQuotesType = .no
    textField.smartDashesType = .no
    textField.smartInsertDeleteType = .no
    textField.textContentType = nil
    textField.autocapitalizationType = .none
    return textField
  }
  
  // Swizzle init(coder:) for storyboard/nib initialization
  static let swizzleInitCoder: Void = {
    let originalSelector = #selector(UITextField.init(coder:))
    let swizzledSelector = #selector(UITextField.swizzled_init(coder:))
    
    guard let originalMethod = class_getInstanceMethod(UITextField.self, originalSelector),
          let swizzledMethod = class_getInstanceMethod(UITextField.self, swizzledSelector) else {
      return
    }
    
    method_exchangeImplementations(originalMethod, swizzledMethod)
  }()
  
  @objc private func swizzled_init(coder: NSCoder) -> UITextField? {
    let textField = self.swizzled_init(coder: coder)
    if let tf = textField {
      tf.autocorrectionType = .no
      tf.spellCheckingType = .no
      tf.smartQuotesType = .no
      tf.smartDashesType = .no
      tf.smartInsertDeleteType = .no
      tf.textContentType = nil
      tf.autocapitalizationType = .none
    }
    return textField
  }
  
  // Initialize swizzling when the extension is loaded
  // This method is called from AppDelegate.swift during app launch
  static func initializeSwizzling() {
    _ = swizzleInit
    _ = swizzleInitCoder
  }
}
