const { withDangerousMod, withXcodeProject } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * Expo config plugin to disable iOS predictive text bar
 * This creates a native Swift file that modifies UITextField behavior
 */
const withDisablePredictiveText = (config) => {
  // First, create the Swift file
  config = withDangerousMod(config, [
    'ios',
    async (config) => {
      const projectRoot = config.modRequest.platformProjectRoot;
      const appPath = path.join(projectRoot, 'ExpoGoApp');
      
      // Create the Swift file that will disable predictive text
      const swiftFilePath = path.join(appPath, 'DisablePredictiveText.swift');
      const swiftCode = `//
// DisablePredictiveText.swift
// Auto-generated by expo config plugin
//
// This file disables the iOS predictive text bar for all TextInputs

import UIKit

// Extension to automatically disable predictive text on UITextField
extension UITextField {
  // Swizzle init(frame:) to disable predictive text
  static let swizzleInit: Void = {
    let originalSelector = #selector(UITextField.init(frame:))
    let swizzledSelector = #selector(UITextField.swizzled_init(frame:))
    
    guard let originalMethod = class_getInstanceMethod(UITextField.self, originalSelector),
          let swizzledMethod = class_getInstanceMethod(UITextField.self, swizzledSelector) else {
      return
    }
    
    method_exchangeImplementations(originalMethod, swizzledMethod)
  }()
  
  @objc private func swizzled_init(frame: CGRect) -> UITextField {
    let textField = self.swizzled_init(frame: frame)
    textField.autocorrectionType = .no
    textField.spellCheckingType = .no
    textField.smartQuotesType = .no
    textField.smartDashesType = .no
    textField.smartInsertDeleteType = .no
    textField.textContentType = nil
    textField.autocapitalizationType = .none
    return textField
  }
  
  // Swizzle init(coder:) for storyboard/nib initialization
  static let swizzleInitCoder: Void = {
    let originalSelector = #selector(UITextField.init(coder:))
    let swizzledSelector = #selector(UITextField.swizzled_init(coder:))
    
    guard let originalMethod = class_getInstanceMethod(UITextField.self, originalSelector),
          let swizzledMethod = class_getInstanceMethod(UITextField.self, swizzledSelector) else {
      return
    }
    
    method_exchangeImplementations(originalMethod, swizzledMethod)
  }()
  
  @objc private func swizzled_init(coder: NSCoder) -> UITextField? {
    let textField = self.swizzled_init(coder: coder)
    if let tf = textField {
      tf.autocorrectionType = .no
      tf.spellCheckingType = .no
      tf.smartQuotesType = .no
      tf.smartDashesType = .no
      tf.smartInsertDeleteType = .no
      tf.textContentType = nil
      tf.autocapitalizationType = .none
    }
    return textField
  }
  
  // Initialize swizzling when the extension is loaded
  // This method is called from AppDelegate.swift during app launch
  static func initializeSwizzling() {
    _ = swizzleInit
    _ = swizzleInitCoder
  }
}
`;

      // Write the Swift file
             fs.writeFileSync(swiftFilePath, swiftCode, 'utf8');
             // Only log in development
             if (process.env.NODE_ENV !== 'production') {
               console.log('✅ Created DisablePredictiveText.swift');
             }

      // Read AppDelegate.swift
      const appDelegatePath = path.join(appPath, 'AppDelegate.swift');
      if (!fs.existsSync(appDelegatePath)) {
        console.warn('AppDelegate.swift not found');
        return config;
      }

      let appDelegateContent = fs.readFileSync(appDelegatePath, 'utf8');

      // Check if we've already added the initialization
      if (!appDelegateContent.includes('UITextField.initializeSwizzling')) {
        // Add initialization call in didFinishLaunchingWithOptions
        // Find the return statement in didFinishLaunchingWithOptions
        const returnMatch = appDelegateContent.match(
          /(\s+return super\.application\(application, didFinishLaunchingWithOptions: launchOptions\)\s*)/
        );

        if (returnMatch) {
          // Insert initialization before the return
          const initCode = `
    // Initialize predictive text disabling
    _ = UITextField.initializeSwizzling()
`;
          appDelegateContent = appDelegateContent.replace(
            returnMatch[0],
            initCode + returnMatch[0]
          );
        }

        // Write the modified AppDelegate
        fs.writeFileSync(appDelegatePath, appDelegateContent, 'utf8');
        console.log('✅ Modified AppDelegate.swift to initialize predictive text disabling');
      } else {
        console.log('AppDelegate.swift already modified');
      }

      return config;
    },
  ]);

  // Then, add the Swift file to the Xcode project
  config = withXcodeProject(config, (config) => {
    const xcodeProject = config.modResults;
    const projectRoot = config.modRequest.platformProjectRoot;
    const appPath = path.join(projectRoot, 'ExpoGoApp');
    const swiftFilePath = path.join(appPath, 'DisablePredictiveText.swift');
    const swiftFileName = 'DisablePredictiveText.swift';

    // Check if file exists
    if (!fs.existsSync(swiftFilePath)) {
      if (process.env.NODE_ENV !== 'production') {
        console.warn(`Swift file not found at ${swiftFilePath}, skipping Xcode project integration`);
      }
      return config;
    }

    try {
      // Find the ExpoGoApp group
      const mainGroup = xcodeProject.findPBXGroupKey({ name: 'ExpoGoApp' });
      if (!mainGroup) {
        if (process.env.NODE_ENV !== 'production') {
          console.warn('ExpoGoApp group not found in Xcode project');
        }
        return config;
      }

      // Check if file already exists in project
      const fileRefs = xcodeProject.hash.project.objects.PBXFileReference || {};
      let existingFileRef = null;
      for (const [key, value] of Object.entries(fileRefs)) {
        if (key.endsWith('_comment')) continue;
        if (value.name === `"${swiftFileName}"` || value.path === swiftFileName) {
          existingFileRef = key;
          break;
        }
      }

      // The path should be ExpoGoApp/DisablePredictiveText.swift to match other files
      const correctPath = `ExpoGoApp/${swiftFileName}`;

      if (!existingFileRef) {
        // Use addSourceFile to add the file (it will create the basic structure)
        const fileRef = xcodeProject.addSourceFile(swiftFileName, {
          target: xcodeProject.getFirstTarget().uuid,
        }, mainGroup);

        // Immediately fix the path to match the structure
        if (fileRef && xcodeProject.hash.project.objects.PBXFileReference) {
          const fileRefObj = xcodeProject.hash.project.objects.PBXFileReference[fileRef];
          if (fileRefObj) {
            fileRefObj.path = correctPath;
          }
        }

        if (process.env.NODE_ENV !== 'production') {
          console.log('✅ Added DisablePredictiveText.swift to Xcode project');
        }
      }

      // Always ensure the path is correct (fixes existing or newly added files)
      // Find the file reference by searching all PBXFileReference entries
      const allFileRefs = xcodeProject.hash.project.objects.PBXFileReference || {};
      let fileRefToFix = existingFileRef;
      
      if (!fileRefToFix) {
        // Find by name or path
        for (const [key, value] of Object.entries(allFileRefs)) {
          if (key.endsWith('_comment')) continue;
          if (value && (value.name === `"${swiftFileName}"` || (value.path && value.path.includes(swiftFileName)))) {
            fileRefToFix = key;
            break;
          }
        }
      }

      if (fileRefToFix) {
        const fileRefObj = xcodeProject.hash.project.objects.PBXFileReference[fileRefToFix];
        if (fileRefObj) {
          // Force update the path - this must happen after addSourceFile
          fileRefObj.path = correctPath;
          // Also ensure name is set correctly
          if (!fileRefObj.name) {
            fileRefObj.name = `"${swiftFileName}"`;
          }
          if (process.env.NODE_ENV !== 'production') {
            console.log('✅ Set correct path for DisablePredictiveText.swift:', correctPath);
          }
        }
      }
    } catch (error) {
      if (process.env.NODE_ENV !== 'production') {
        console.warn('Error adding Swift file to Xcode project:', error.message);
      }
    }

    return config;
  });

  // Configure build settings to generate dSYM files
  config = withXcodeProject(config, (config) => {
    const xcodeProject = config.modResults;
    const target = xcodeProject.getFirstTarget();
    
    if (target) {
      // Set DEBUG_INFORMATION_FORMAT to dwarf-with-dsym for both Debug and Release
      const configurations = xcodeProject.pbxXCBuildConfigurationSection();
      
      Object.keys(configurations).forEach(configUuid => {
        if (configUuid.endsWith('_comment')) return;
        
        const configObj = configurations[configUuid];
        if (configObj && configObj.buildSettings) {
          // Set for all configurations (Debug, Release, etc.)
          configObj.buildSettings.DEBUG_INFORMATION_FORMAT = 'dwarf-with-dsym';
        }
      });

      if (process.env.NODE_ENV !== 'production') {
        console.log('✅ Configured dSYM generation in Xcode build settings');
      }
    }

    return config;
  });

  return config;
};

module.exports = withDisablePredictiveText;
